### ISSUE TITLE
React component

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-button#11]
It will be nice to have a react component wrapper. I can help with that.

**Comment by davidyuk** [comment]
Would be nice to implement it without explicit dependency on react (~like a functional component?~)

**Comment by shapkarin** [comment]
@davidyuk I see two ways:
- change this project API to fit with react and create react component next
- create react's one from scratch

I need this for [that integration](https://github.com/aeternity/jitsi-meet/issues/21) and I'm afraid that my current integration with this lib can cause problems with garbage collector.

**Comment by shapkarin** [comment]
@davidyuk let's decide what will be better for a future maintaining. Also I can to help with that task #4

**Comment by davidyuk** [comment]
> change this project API to fit with react

What is the issue here? I think it is already implemented in a way compatible with React/Vue and other use cases.

> I'm afraid that my current integration with this lib can cause problems with garbage collector

Can you send a link exactly to that integration for review? Won't superhero-button be collected after removing the corresponding node from DOM?

**Comment by shapkarin** [comment]
> What is the issue here? I think it is already implemented in a way compatible with React/Vue and other use cases. 

There is no issue. I think think to export some methods to make them available.

>Can you send a link exactly to that integration for review? Won't superhero-button be collected after removing the corresponding node from DOM?

You can check the current integration at:
 https://github.com/aeternity/jitsi-meet/compare/jwt_with_detector...aeternity:tip_button

**Comment by shapkarin** [comment]
@davidyuk I use call `superheroButton ` every time when speaker changed.
