### ISSUE TITLE
Add react version @aeternity/superhero-button/react

### ISSUE THREAD

**Issue by shapkarin** [aeternity/superhero-button#21]
Make [that repo](https://github.com/aeternity/superhero-button-react) a part of this one. To make it easier to integrate button in any kind of projects that use sdk.
Not only our jitsi or forks

**Comment by davidyuk** [comment]
related issue: #11

**Comment by shapkarin** [comment]
@davidyuk so we agree to add React and maybe later Vue as part of this repo and npm package but at separate folders and without export to the [main](https://github.com/aeternity/superhero-button/blob/master/package.json#L5)?

**Comment by davidyuk** [comment]
Yes, I think so. 
https://github.com/aeternity/superhero-button-react/issues/2#issuecomment-656545493

**Comment by shapkarin** [comment]
> Yes, I think so.

OK. I will do that after the https://github.com/aeternity/jitsi-meet/issues/166

**Comment by shapkarin** [comment]
sorry, thought that it's duplicate

**Comment by davidyuk** [comment]
implemented in #38 🎉
