### ISSUE TITLE
Lead to browser extension store page

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-button#8]
If there is no extension detected - clicking on the Donate button URL redirect should be leading to the corresponding browser extension store page for the Superhero wallet.

**Comment by davidyuk** [comment]
Actually, did we implemented wallet detection somehow?

**Comment by petarbaykov** [comment]
> Actually, did we implemented wallet detection somehow?

There is no wallet extension detection from website script. The link of the button is set to web wallet or store link. If wallet detects superhero button link - prevents its default behavior and opens tip popup
